enum authorities {
  MYLISTENTRY_DELETE_ALL = "MYLISTENTRY_DELETE_ALL",
  MYLISTENTRY_DELETE_OWN = "MYLISTENTRY_DELETE_OWN",
  MYLISTENTRY_MODIFY_ALL = "MYLISTENTRY_MODIFY_ALL",
  MYLISTENTRY_MODIFY_OWN = "MYLISTENTRY_MODIFY_OWN",
  MYLISTENTRY_READ_ALL = "MYLISTENTRY_READ_ALL",
  USER_DELETE_ALL = "USER_DELETE_ALL",
  USER_DELETE_OWN = "USER_DELETE_OWN",
  USER_MODIFY_ALL = "USER_MODIFY_ALL",
  USER_MODIFY_OWN = "USER_MODIFY_OWN",
  USER_READ_ALL = "USER_READ_ALL",
}

export default authorities
